apiVersion: v1
kind: Secret
metadata:
  name: wundr-secrets
  namespace: wundr
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME_32+_CHARS________________"
  DATABASE_URL: "postgres://USER:PASSWORD@HOST:5432/DB"
  REDIS_URL: "redis://HOST:6379"
